### ISSUE TITLE
DUMLdore  V3.07 Unhandled exception when activating Spark

### ISSUE THREAD

**Issue by KreativeLabs** [jezzab/DUMLdore#32]
Hello,

I am trying to activate a Spark on Windows 7. When I click on Activate, an unhandled exception popup shows and I cannot activate Spark.

Here is the error log it gives me:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at DUMLdoreV3.Form1.btnActivate_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jezzab** [comment]
I have tested on a Spark here and replicate the issue. I am working on a fix.
Please try the previous release here in the mean time:
https://github.com/jezzab/DUMLdore/releases/tag/v3.051

**Comment by KreativeLabs** [comment]
Thanks, it worked :)
